# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/karchive': '@stable'
    'graphics/libkexiv2': '@same'
    'graphics/libkdcraw': '@same'
    'graphics/kdegraphics-mobipocket': '@same'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'graphics/libkexiv2': '@same'
    'graphics/libkdcraw': '@same'
    'graphics/kdegraphics-mobipocket': '@same'
