# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'graphics/libkexiv2': '@same'
    'graphics/libkdcraw': '@same'
    'graphics/kdegraphics-mobipocket': '@same'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
